Linux cammand:
1.  pwd     => It displays the current working location or directory of the user
2.  ls      => The ls command is used to show the list of a folder. It will list out all the files in the directed folder.
3.  cd      => The cd command stands for (change directory). It is used to change to the directory you want to work from the present directory.
4.  mkdir   => mkdir command you can create your own directory.
5.  rmdir   => The rmdir command is used to remove a directory from your system.
6.  cd~     => Brings you to your home directory.
7.  cd -    => Brings you to your previous directory of the current directory.
8.  cd..    => Brings you to the parent directory of current directory.
9.  cd /    => It takes you to the entire system's root directory.here / mens root directroy
10. ls-a   => In Linux, hidden files start with . (dot) symbol and they are not visible in the regular directory. The (ls -a) command will enlist the whole list of the current directory including the hidden files.
11. ls-l   => It will show the list in a long list format.
12. ls-lh  => This command will show you the file sizes in human readable format. 
13. ls-lhs => If you want to display your files in descending order
14. ls-d*/ => It is used to display only sub directories.
15  ls-n   => It is used to print group ID and owner ID instead of their names.
16  ls-r   => It is used to print the list in reverse order.
17  ls-R   => It will display the content of the sub-directories also.
18  ls~    => It gives the contents of home directory.
19  ls ../ =>  give the contents of parent directory.
20  ls-version => It checks the version of ls command.
21  mkdir -p => With the help of mkdir -p command you can create sub-directories of a directory
22  mkdir-r  => Print a message for each created directory.
23  man      => A user can request to display a man page by simply typing man followed by a space and then argumen
24  cal      => it will show the calender
25  clear    => it will clear the screen
26  Cat      => The tool is mostly used for displaying contents of a file  we can also create the file by using cat cammand.
27  Rm       => it is used to remove file 
28  Cp       => it used to copy file and directory from one location to another location or one directory to other directory
29  mv       => it can be use move file and directory
30  Less     => it is somthing like cat cmmand but some diffrent
31  Touch    => it is used to creat a file and only empty file
32  Nano     => it can be also use creat a file
33  sudo     => it will use to if we want to most privilage
34  Top      =>  we can use to check our processor information
35  KILL     => we can use this one to kill our process by useing process id
36 Echo      => it can be use to echo some string or create tampory variable
37 Date      => it use to show the current date
38 Time      => it will display time
         